#!/usr/bin/env node
/**
 * Build-time generator: read image-assets.json and emit
 * src/lib/r2-media-map.generated.ts with ONLY the {filename → R2 URL}
 * data needed by the Media collection's afterRead hook.
 *
 * The full manifest is ~1.3 MB because every entry carries a base64
 * `test_preview` thumbnail used by tools/image-generator-ui. Importing
 * that JSON directly into the Next server bundle inflates the Netlify
 * Lambda by the same 1.3 MB and parses ~3 MB of strings on every cold
 * start — enough to push the function over its memory budget on small
 * plans and produce 500s.
 *
 * The generated file is ~3 KB (just the URL strings) and gets stitched
 * cleanly into the bundle. It's regenerated automatically by the
 * `prebuild` and `predev` npm scripts.
 *
 * Usage: node scripts/generate-r2-map.mjs
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')
const manifest = JSON.parse(
  fs.readFileSync(path.join(root, 'image-assets.json'), 'utf8'),
)

function extOf(url) {
  try {
    return path.posix.extname(new URL(url).pathname) || '.webp'
  } catch {
    return '.webp'
  }
}

const map = new Map()

// Pass 1: every uploaded entry under its own filename.
for (const img of manifest.images || []) {
  if (img.status !== 'uploaded' || !img.result_url) continue
  map.set(`${img.id}${extOf(img.result_url)}`, img.result_url)
}

// Pass 2: alias overrides. If a -realistic entry exists with aliasOf=<v1id>,
// remap the v1 filename to the realistic URL.
for (const img of manifest.images || []) {
  if (img.status !== 'uploaded' || !img.result_url || !img.aliasOf) continue
  map.set(`${img.aliasOf}.webp`, img.result_url)
}

const lines = [...map.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join('\n')

const out = `// AUTOGENERATED by scripts/generate-r2-map.mjs — do not edit by hand.
// Regenerate after image-assets.json changes (npm run dev / build does this for you).
/* eslint-disable */
export const r2MediaMap: Record<string, string> = {
${lines}
}
`

const outPath = path.join(root, 'src', 'lib', 'r2-media-map.generated.ts')
fs.writeFileSync(outPath, out)
console.log(`Wrote ${map.size} entries → src/lib/r2-media-map.generated.ts`)
